"""initial pos schema

Revision ID: 282982afbef1
Revises: 
Create Date: 2026-09-11 12:24:04.862013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282982afbef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_masters',
    sa.Column('color_system_id', sa.String(length=32), nullable=False),
    sa.Column('color_code', sa.String(length=16), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('color_system_id', 'color_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('member_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('point_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('default_price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('size_system_id', sa.String(length=32), nullable=True),
    sa.Column('color_system_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('size_masters',
    sa.Column('size_system_id', sa.String(length=32), nullable=False),
    sa.Column('size_code', sa.String(length=16), nullable=False),
    sa.Column('size_name', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('size_system_id', 'size_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.String(length=32), nullable=False),
    sa.Column('staff_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STAFF', 'MANAGER', 'ADMIN', name='roleenum'), server_default=sa.text("'STAFF'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('tax_rates',
    sa.Column('tax_rate_id', sa.String(length=32), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tax_validity', 'tax_rates', ['valid_from', 'valid_to'], unique=False)
    op.create_table('skus',
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('barcode_ean13', sa.String(length=13), nullable=False),
    sa.Column('size_system_id', sa.String(length=32), nullable=False),
    sa.Column('size_code', sa.String(length=16), nullable=False),
    sa.Column('color_system_id', sa.String(length=32), nullable=False),
    sa.Column('color_code', sa.String(length=16), nullable=False),
    sa.Column('store_stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warehouse_stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('store_stock >= 0', name='chk_stock'),
    sa.ForeignKeyConstraint(['color_system_id', 'color_code'], ['color_masters.color_system_id', 'color_masters.color_code'], name='fk_sku_color', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_sku_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_system_id', 'size_code'], ['size_masters.size_system_id', 'size_masters.size_code'], name='fk_sku_size', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sku_id'),
    sa.UniqueConstraint('barcode_ean13'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_product', 'skus', ['product_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('staff_id', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CREDIT_CARD', 'QR_CODE', 'IC', name='paymentmethodenum'), nullable=False),
    sa.Column('subtotal_ex_tax', sa.Integer(), nullable=False),
    sa.Column('discount_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_inc_tax', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('SALE', 'RETURN', 'EXCHANGE', name='transactiontypeenum'), server_default=sa.text("'SALE'"), nullable=False),
    sa.Column('parent_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], name='fk_tx_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transactions.transaction_id'], name='fk_tx_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_tx_staff', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_created', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_member', 'transactions', ['member_id'], unique=False)
    op.create_table('discount_masters',
    sa.Column('discount_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.Enum('SKU', 'PRODUCT', 'MEMBER', name='discounttargettypeenum'), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('sku_id', sa.String(length=64), nullable=True),
    sa.Column('discount_type', sa.Enum('RATE', 'AMOUNT', name='discounttypeenum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_discount_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], name='fk_discount_sku', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('discount_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_discount_target', 'discount_masters', ['target_type', 'product_id', 'sku_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('inventory_histories',
    sa.Column('inventory_history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'SALE', 'RETURN', 'TRANSFER', 'ADJUSTMENT', name='movementtypeenum'), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('staff_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], name='fk_inv_sku', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_inv_staff', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], name='fk_inv_transaction', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_history_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_inventory_sku_time', 'inventory_histories', ['sku_id', 'created_at'], unique=False)
    op.create_index('idx_inventory_transaction', 'inventory_histories', ['transaction_id'], unique=False)
    op.create_table('price_histories',
    sa.Column('price_history_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_price_prod', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], name='fk_price_sku', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('price_history_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_price_target', 'price_histories', ['product_id', 'sku_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('sales_items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Integer(), nullable=False),
    sa.Column('discount_amount_snapshot', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount_snapshot', sa.Integer(), nullable=False),
    sa.Column('line_total_ex_tax', sa.Integer(), nullable=False),
    sa.Column('line_total_inc_tax', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_item_prod', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], name='fk_item_sku', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], name='fk_item_tx', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # DROP TABLE removes the table's own indexes; dropping them separately first fails
    # on MySQL because several of them back an InnoDB foreign key.
    op.drop_table('sales_items')
    op.drop_table('price_histories')
    op.drop_table('inventory_histories')
    op.drop_table('discount_masters')
    op.drop_table('transactions')
    op.drop_table('skus')
    op.drop_table('tax_rates')
    op.drop_table('staff')
    op.drop_table('size_masters')
    op.drop_table('products')
    op.drop_table('members')
    op.drop_table('color_masters')
