"""add unique constraint on sku product size color

Revision ID: 708b74c1cb7c
Revises: e50042f113f2
Create Date: 2026-09-19 22:48:39.120005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708b74c1cb7c'
down_revision: Union[str, None] = 'e50042f113f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sku_product_size_color', 'skus', ['product_id', 'size_code', 'color_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sku_product_size_color', 'skus', type_='unique')
    # ### end Alembic commands ###
