"""add is_active to products and skus

Revision ID: 936f0e6b6f53
Revises: 282982afbef1
Create Date: 2026-09-11 12:44:16.011304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936f0e6b6f53'
down_revision: Union[str, None] = '282982afbef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('skus', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'is_active')
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
